# -*- coding: utf-8 -*-
"""Semantic_Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVegBYwEvUVfOXDp92OJecURaY5NE4qp
"""

!pip install pandas sentence-transformers faiss-cpu openpyxl

import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import os

file_path = "/content/Qur'an Dataset.xlsx"
df = pd.read_excel(file_path)
df.dropna(subset=["Verse"], inplace=True)

embeddings_file = "verse_embeddings.npy"
model_name = 'all-MiniLM-L6-v2'
if os.path.exists(embeddings_file):
    print("[INFO] Loading cached embeddings from file...")
    embeddings = np.load(embeddings_file)
    model = SentenceTransformer(model_name)
else:
    print("[INFO] Generating embeddings for all verses...")
    model = SentenceTransformer(model_name)
    embeddings = model.encode(df["Verse"].tolist(), show_progress_bar=True)
    np.save(embeddings_file, embeddings)
    print("[INFO] Embeddings saved for future use.")

dim = embeddings.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(np.array(embeddings).astype('float32'))

print("[READY] Semantic Search Initialized!")

while True:
    query = input("\nEnter your search query (or type 'exit'): ")
    if query.lower() == 'exit':
        break
    query_embedding = model.encode([query])
    D, I = index.search(np.array(query_embedding).astype('float32'), 5)

    print("\nTop relevant verses:\n")
    for i in I[0]:
        verse_info = df.iloc[i]
        print(f"[Surah {verse_info['Name']} ({verse_info['Surah']}), Ayah {verse_info['Ayat']}]:\n{verse_info['Verse']}\n")

